# Math Operation

* dot : 벡터 내적 

* mv : 행렬과 벡터의 곱

* mm : 행렬과 행렬의 곱

* matmul : 인수의 종류에 따라서 자동으로 dot, mv, mm을 선택

In [4]:
import torch

a = torch.tensor([1,2,3,4,5,6]).view(3,2)

b = torch.tensor([9,8,7,6,5,4]).view(2,3)

ab = torch.matmul(a,b)

ab = a @ b

* Tensor의 산술 연산 방법에 대하여 알아보겠습니다.

* + 연산자 또는 torch.add()

In [5]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])

add = x1 + x2

print(add)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


* + 연산자를 이용한 broadcasting 또는 torch.add() with broadcasting

In [10]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])

x1 + 10

# torch.add(x1, 10)

tensor([[11., 12., 13.],
        [14., 15., 16.]])

* '*' 연산자 또는 torch.mul()

In [14]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])

x1*10

torch.mul(x1,x2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

* '*' 연산자를 이용한 broadcasting 또는 torch.mul() with broadcasting

In [13]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])
x2 = torch.FloatTensor([[1,2,3], [4,5,6]])

x1 / x2

torch.div(x1, x2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

* power 연산 : torch.pow(input, exponent)

In [16]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])

x1 ** 2

torch.pow(x1, 2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

* exponentioal 연산 : torch.exp(tensor, out=None)

In [17]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])

torch.exp(x1)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [18]:
x1 = torch.FloatTensor([[1,2,3], [4,5,6]])

torch.log(x1)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

##### torch.mm(mat1, mat2) -> matrix multiplication
##### Tensor(행렬)의 곱을 연산하므로 shape이 잘 맞아야 연산이 가능합니다. 

In [19]:
x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2).size()

torch.Size([3, 5])

##### torch.bmm(batch1, batch2) -> batch matrix multiplication 

* Tensor(행렬)의 곱을 batch 단위로 처리합니다. torch.mm에서는 단일 Tensor(행렬)로 계산을 한 반면에 batch 단위로 한번에 처리하므로 좀 더 효율적입니다. 

In [22]:
x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

* torch.t()를 이용하면 transposed tensor를 구할 수 있다.

In [26]:
x1 = torch.FloatTensor(2,3)
x2 = x1.t()

print(x1.size())
print(x2.size())

torch.Size([2, 3])
torch.Size([3, 2])


* 반면 torch.transpose()를 이용하여 특정 dimension을 변경할 수 있습니다.

In [30]:
x1 = torch.FloatTensor(10,3,4,5)
x1.size()

torch.transpose(x1,1,2).size()

torch.transpose(x1,2,3).size()

torch.Size([10, 3, 5, 4])

* eigenvalue와 eigenvector 를 구하는 방법은 아래와 같다. 

* 출력은 각각 eigenvalue와 eigenvector 입니다.

In [32]:
x1 = torch.FloatTensor(4,4)